### ISSUE TITLE
RecentContactsFragment 列表为空，死活出不来！

### ISSUE THREAD

**Issue by FridayCXD** [netease-im/NIM_Android_UIKit#33]

**Comment by manburenshenglu** [comment]
> _No description provided._

怎么解决的？MsgDatabase is not opened. Please login first!Z这是没登录的意思吗

**Comment by gitfdy** [comment]
> > _No description provided._
> 
> 怎么解决的？MsgDatabase is not opened. Please login first!Z这是没登录的意思吗

这个有解决吗

**Comment by gitfdy** [comment]
遇到了同样的问题

**Comment by ling9400** [comment]
最后到底是怎么解决的呢？ 也是报数据的错
