### ISSUE TITLE
第一次见到如此垃圾的SDK...见识了

### ISSUE THREAD

**Issue by liu12151407** [netease-im/NIM_Android_UIKit#48]
如题

**Comment by liu12151407** [comment]
https://github.com/netease-im/NIM_Android_UIKit/issues/27

**Comment by DevXue** [comment]
2017年的时候准备接入聊天功能，那会看了下这个SDK， 写的真是TMD一坨狗屎，现在还是这个鸟样子·· 我TM醉了。。

**Comment by restmad** [comment]
希望官方继续努力

**Comment by iosLongFeng** [comment]
和ios比真的是垃圾的一逼

**Comment by liu12151407** [comment]
付费后的最差SDK体验，关闭了吧
