### ISSUE TITLE
Gralde添加依赖以后运行项目出现Entry name "assets/sm2/t.jks" collide错误

### ISSUE THREAD

**Issue by lykAnd** [netease-im/NIM_Android_UIKit#54]
项目Gradle添加7.4.0版本的依赖后,运行项目的时候出现**Execution failed for task ':app:packageDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > java.lang.IllegalStateException: Entry name 'assets/sm2/r.jks' collided**.

**Comment by lykAnd** [comment]
依赖的是7.4.0的SDK

**Comment by lykAnd** [comment]
还有一个问题。为什么依赖UIKit以后没有初始化，自己的项目里面用到Glide的时候，出现了
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.netease.nim.uikit.common.util.log.sdk.LogBase.i(java.lang.String, java.lang.String)' on a null object reference
        at com.netease.nim.uikit.common.util.log.sdk.wrapper.AbsNimLog.i(AbsNimLog.java:52)
异常
看起来只是一个Log的东西，为什么一定要要求初始化

**Comment by xyz-fly** [comment]
工程使用com.android.tools.build:gradle:3.5.3则可以编译过
工程使用com.android.tools.build:gradle:3.6.2则编译不过

**Comment by lykAnd** [comment]
> 工程使用com.android.tools.build:gradle:3.5.3则可以编译过
> 工程使用com.android.tools.build:gradle:3.6.2则编译不过

这个我用官方demo测试过了，用改成androidx之前的版本（好像是3.6.9之前吧），gradle依赖都正常。改成andoridx之后的都出现这个问题。要用demo那种添加jar包的方式才能用。

**Comment by xyz-fly** [comment]
> > 工程使用com.android.tools.build:gradle:3.5.3则可以编译过
> > 工程使用com.android.tools.build:gradle:3.6.2则编译不过
> 
> 这个我用官方demo测试过了，用改成androidx之前的版本（好像是3.6.9之前吧），gradle依赖都正常。改成andoridx之后的都出现这个问题。要用demo那种添加jar包的方式才能用。

其实，还有一种解决方案，就是还是使用最新的android tool gradle ，这样不会影响其工程整体，比如使用viewbinding。
然后，在gradle.properties中，加一行：android.useNewApkCreator=false   就可以编译通过了

引用官方说明如下：
Android 构建团队一直在努力的改进构建性能，在这个版本中，将开发调试模式时的默认打包工具改为了 zipflinger。这样在调试开发的时候构建速度将会有所提高，但是我们也可以在gradle.properties 文件中设置 android.useNewApkCreator=false 来改用旧的打包工具。

**Comment by aw220** [comment]
> > > 工程使用com.android.tools.build:gradle:3.5.3则可以编译过
> > > 工程使用com.android.tools.build:gradle:3.6.2则编译不过
> > 
> > 
> > 这个我用官方demo测试过了，用改成androidx之前的版本（好像是3.6.9之前吧），gradle依赖都正常。改成andoridx之后的都出现这个问题。要用demo那种添加jar包的方式才能用。
> 
> 其实，还有一种解决方案，就是还是使用最新的android tool gradle ，这样不会影响其工程整体，比如使用viewbinding。
> 然后，在gradle.properties中，加一行：android.useNewApkCreator=false 就可以编译通过了
> 
> 引用官方说明如下：
> Android 构建团队一直在努力的改进构建性能，在这个版本中，将开发调试模式时的默认打包工具改为了 zipflinger。这样在调试开发的时候构建速度将会有所提高，但是我们也可以在gradle.properties 文件中设置 android.useNewApkCreator=false 来改用旧的打包工具。

方法有效，我跟题主一样的错误，我刚刚实测不报错了

**Comment by lykAnd** [comment]
等有空了再来试试。感谢楼上二位大佬帮忙。手动点赞 ！！
